import Head from "next/head";
import Appetizer from "../components/appetizer";
import Banner from "../components/banner";
import CopyRight from "../components/copyright";
import Discount from "../components/discount";
import FavoriteFood from "../components/favoriteFood";
import Footer from "../components/footer";
import Header from "../components/header";
import NewFood from "../components/newfood";
import ProminentService from "../components/prominentService";
import Salad from "../components/salad";
import Slide from "../components/slide";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.wapper}>
        <div className={styles.container}>
          <Header />
          <Banner />
          <NewFood />
          <FavoriteFood />
          <Appetizer />
          <Salad />
          <ProminentService />
          <Slide />
          <Footer />
          <CopyRight />
        </div>
      </main>
    </div>
  );
}
